Bump syntax_tree from 2.7.1 to 2.8.0
Shopify/ruby-lsp pull request #164
Opened 2022-06-22 12:34 UTC by wildmaples

### Motivation

Bumps [syntax_tree](https://github.com/kddnewton/syntax_tree) from 2.7.1 to 2.8.0

I need the changes for this PR - https://github.com/Shopify/ruby-lsp/pull/161

### Implementation

N/A 

### Automated Tests

N/A

### Manual Tests

N/A

2022-06-22 13:19 UTC, st0012 approved these changes

2022-06-22 13:27 UTC, RyanBrushett requested changes
Isn't this needed for a feature at runtime? That should be in the gemspec no? Since we'll be adding a hard dependency on this version of syntax_tree?

2022-06-22 13:41 UTC, RyanBrushett commented
From a technical perspective, it doesn't matter until release anyway and IMO it would be confusing to bump the same gem to a specific version in two separate PRs. Plus, this PR actually links to the feature anyway so IMO let's just bump it properly here.

2022-06-23 11:15 UTC, wildmaples commented
Thanks all - closing this PR and bumping the versions on the feature PR.

2022-06-23 11:15 UTC, closed without merging