vscode/asdf: support configuration environment variables
Shopify/ruby-lsp pull request #2029
Opened 2024-05-10 06:51 UTC by gi

This adds support for detecting asdf configuration via its environment variables:
* ASDF_DIR: installation location
* ASDF_DATA_DIR: data directory

### Motivation

Fixes #2023 

### Implementation

If the environment variable is set, include it as the first option for where to search to validate the value.

### Automated Tests

### Manual Tests

2024-05-10 06:55 UTC, gi commented
I have signed the CLA!

2024-05-10 15:18 UTC, vinistock requested changes
Thank you for the contribution!

This approach would only work if the user opens VS Code through the terminal so that it can inherit the environment of the current shell.

Otherwise, VS Code's environment wouldn't include these environment variables - especially if they are set using shell scripts (which are not sourced automatically by the VS Code process, they are only source by the terminal).

If `ASDF_DIR` and `ASDF_DATA_DIR` can be override and that's a common thing to do, then the answer is to provide new settings so that users can configure that themselves.

Here's an example of how to do it https://github.com/Shopify/ruby-lsp/pull/1976.

2024-05-10 17:01 UTC, gi commented
@vinistock Thanks for the feedback.

FYI, a recent update broke this customization of the `asdf` setup.

I presume that it was this commit: [30bc0001](https://github.com/Shopify/ruby-lsp/commit/30bc0001b1085463d7bb420756c2de662c34202b).

I'm simply comparing the timeframe of the commit and the functionality change. (I use Ruby LSP every day.)

2024-05-10 17:03 UTC, gi commented
@vinistock Shouldn't the shell be able to determine the values of the `ASDF_DIR` and `ASDF_DATA_DIR` values, so why are they manually set?

2024-05-10 17:48 UTC, vinistock commented
We have decoupled all version manager integrations from shells. I explained in more detail [here](https://github.com/Shopify/ruby-lsp/pull/1976#issuecomment-2086120032). The summary is that trying to automatically discover the user's shell and source their configurations has lead to several problems and it's generally a brittle approach. The NodeJS process where extensions run is not the same as your shell/terminal. Nothing you configure in shell scripts is available there.

We're trying to push forward version manager integrations that do not connect to the shell in any way, so that we can achieve more reliable environment activation.

Compared to other version managers, ASDF is proving to be extremely coupled with shells (multiple users have raised issues). It seems that when we source the `asdf.sh` script from the NodeJS `exec` invocation (which uses `/bin/sh`), ASDF is not able to properly determine `ASDF_DIR` and `ASDF_DATA_DIR` automatically, which I believe is the source of many of the errors we're seeing.

If you have better ideas on how to make the integration smoother, please do tell us.

2024-05-10 17:54 UTC, gi commented
@vinistock I pushed an update with an alternative approach. I'm not sure this will work either based on the complexities you mentioned, but I'm curious on your insights.

2024-05-13 06:11 UTC, gi commented
I created an alternative and simpler update which simply includes the XDG base data directory as it is a common pattern: https://github.com/Shopify/ruby-lsp/pull/2045.

2024-05-30 21:28 UTC, closed without merging