Add neovim-lspconfig instructions
Shopify/ruby-lsp pull request #713
Opened 2023-05-09 21:54 UTC by tnightingale

### Motivation

Adding configuration instructions for Neovim (via neovim-lspconfig) as per [this comment](https://github.com/Shopify/ruby-lsp/issues/188#issuecomment-1456941648).

### Implementation

Just adding documentation.

2023-05-09 22:27 UTC, andyw8 requested changes

2023-05-09 22:27 UTC, andyw8 commented on EDITORS.md
> +- Install [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) via your favourite plugin manager (eg: [Packer](https://github.com/wbthomason/packer.nvim)).
```suggestion
- Install [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) using your preferred plugin manager.
```
(I think we can trust people will already have one configured).

2023-05-09 22:27 UTC, andyw8 commented on EDITORS.md
> +    -- Add your lspconfig configurations/overrides here, eg:
```suggestion
    -- Add your lspconfig configurations/overrides here, e.g.:
```

2023-05-09 22:30 UTC, andyw8 commented
I'm not familiar with neovim, so it would be helpful if we have could someone else from the [discussion](https://github.com/neovim/nvim-lspconfig/pull/2498) to verify this and add a comment here.

2023-05-25 17:47 UTC, vinistock commented
Is dealing with `textDocument/diagnostic` the main source of disagreement in the discussions? If that's the main thing and this config works for everything else, I'd say let's move forward and people can put up PRs against the existing instructions to enhance it.

It's been a long time since the discussion started. At this point, it's better to have something than nothing in our instructions.

2023-07-25 13:15 UTC, andyw8 commented
Hi @tnightingale, I'll close this since Neovim instructions were merged in https://github.com/Shopify/ruby-lsp/pull/830. Feel free to open a new PR if there's anything you can think can be improved.

2023-07-25 13:15 UTC, closed without merging